[[redirects]]
  from = "https://fain-avocats.fr/*"
  to = "https://www.fain-avocats.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://fain-avocats.fr/*"
  to = "https://www.fain-avocats.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.fain-avocats.fr/*"
  to = "https://www.fain-avocats.fr/:splat"
  status = 301
  force = true

[build]
  command = "npm run build"
  publish = ".next"
